### ISSUE TITLE
Active pipelines indicator

### ISSUE THREAD

**Issue by blueimp** [buildkite/frontend#103]
Hi Buildkite team,
really like the new pipelines view, but I miss two small aspects that were very useful in the old one:
- Could you give the icon at the front of a pipeline an indicator again if it's currently building?
- Also it was a neat feature that pipelines who are active would move to the top of the list.

Thanks for your consideration!

**Comment by toolmantim** [comment]
Thanks for the feedback @blueimp!

**Comment by keithpitt** [comment]
> Could you give the icon at the front of a pipeline an indicator again if it's currently building?

We shipped this a little while ago and forgot to update this ticket!

**Comment by blueimp** [comment]
Thanks! 👍
