### ISSUE TITLE
Emoji not rendering

### ISSUE THREAD

**Issue by ineffyble** [buildkite/frontend#132]
Following the guides at https://buildkite.com/docs/builds/managing-log-output , I've added the following line to our build shell script:

`echo -e "\:package: Deploying to dev environment"`

However, it is showing verbatim, and not showing any emoji. Removing the backslash escape has no effect.

**Comment by toolmantim** [comment]
Oh darn, we might have broken our docs there. Sorry about that!

Can you try this instead: `echo ":package: Deploying to dev environment"`

**Comment by ineffyble** [comment]
No luck I'm afraid.
![image](https://cloud.githubusercontent.com/assets/834880/20646075/56bcd3dc-b4c7-11e6-8bfc-e732c59b05bc.png)
![image](https://cloud.githubusercontent.com/assets/834880/20646080/723bae08-b4c7-11e6-94d4-e194c1f91313.png)

**Comment by toolmantim** [comment]
Oh wait, it needs to be a group. It's missing the `---`

```
echo "--- :package: Deploying to dev environment"
```

**Comment by ineffyble** [comment]
Interesting - it's working in group headings, but not in the logs underneath them.
![image](https://cloud.githubusercontent.com/assets/834880/20646111/1b7482a6-b4c8-11e6-8734-a5a5977729b0.png)

**Comment by toolmantim** [comment]
That's by design I'm afraid!

**Comment by ineffyble** [comment]
Alas ![sadpanda](https://raw.githubusercontent.com/buildkite/emojis/master/img-buildkite-64/sadpanda.png)

**Comment by toolmantim** [comment]
Sorry! But I'm going to reopen this just so @harrietgrace can check our docs are still telling the truth with the emoji syntax. Those blackslashes don't look quite right.

**Comment by ticky** [comment]
I recall we were having some issues with

- escaping emoji
  - in YAML snippets
    - in Markdown processed by the Ruby app

remove one of those and it worked okay. I suspect the situation will change when the new tech hits, but that’s worth double-checking, too!

**Comment by harrietgrace** [comment]
Yeah, we ended up sorting out that particular issue @ticky 🎉 But these docs do need to be updated, there are some accidental slashes in there!
