### ISSUE TITLE
Non-breaking text flowing out of build log container

### ISSUE THREAD

**Issue by maschwenk** [buildkite/frontend#146]
![image](https://cloud.githubusercontent.com/assets/1264305/21697544/b9efe9c8-d347-11e6-87b3-7dc9f3000f0e.png)

**Comment by maschwenk** [comment]
Any ideas here?

**Comment by ticky** [comment]
Hmm, very odd, what version of Firefox are you using? That output seems to work okay for me in Firefox!

**Comment by maschwenk** [comment]
I'm not sure of the best way to repro. Maybe just load up a very large RSpec run? I don't think we're doing anything too special...maybe I'll ask in the Slack channel.

**Comment by ticky** [comment]
Looks like there’s a regression with `word-break` in Chrome 56. No other browser appears to behave this way except Blink-based ones. Really strange!

**Comment by ticky** [comment]
I’ve made [a small test case](https://jsfiddle.net/ticky/n2my41q5/) which reproduces this issue. Going to send a bug report to Chrome and hope that gets somewhere…

**Comment by ticky** [comment]
Posted to [Chromium’s bug tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=687338), let us hope it gets somewhere.

**Comment by keithpitt** [comment]
Oh, I fixed this with some hacks last week :) Should be fine now!
