### ISSUE TITLE
'Waiting for' calculation seems wrong

### ISSUE THREAD

**Issue by jnewbigin** [buildkite/frontend#165]
I left a build running while I was on holidays. There was no agent running so it was waiting from Jan 17 -> Feb 1 = 15 days, or around 2 weeks.

However, the pipeline says 'Waiting for 4 weeks'
and the build says waiting for '2w 15d'

I suspect that 15 days is being converted to 2w but the days are not being set to the remainder.

Then I suspect they are being added back together to get the 4 weeks value.
![buildkite](https://cloud.githubusercontent.com/assets/7644148/22494184/83b3b37e-e889-11e6-97d6-8342891c9a12.png)
![buildkite2](https://cloud.githubusercontent.com/assets/7644148/22494189/8d7cc350-e889-11e6-9a77-56c7e254ca5a.png)

**Comment by keithpitt** [comment]
Oh! You're possibly 100% correct :P

I know @ticky has played with that code quite a bit - wanna take a sneaky look?

**Comment by ticky** [comment]
How ‘bout a sneaky pull request? 😜 #166

Unfortunately, Moment doesn’t quite allow using its own formatters to build the duration formatting we want, so we had to improvise, and it turns out that had some downsides… Anyway, this PR should fix it right up!

**Comment by keithpitt** [comment]
I can get on board with sneaky pull requests!

**Comment by jnewbigin** [comment]
Looks good! Everything is now showing as expected.
