### ISSUE TITLE
Gravatar should use lowercase email address

### ISSUE THREAD

**Issue by mpsijm** [buildkite/frontend#285]
Hi there,

I saw that Buildkite uses Gravatar to fetch profile pictures.
I happen to have an account at Gravatar, so I was surprised that my avatar wasn't fetched.
Decided to figure out why this was the case: on sign-up, I entered my email address with uppercase letters, but Gravatar only works with lowercase.
Gravatar documentation: [https://en.gravatar.com/site/implement/hash/](https://en.gravatar.com/site/implement/hash/)

I found this out by inspecting the URL of my profile image, which turned out to be:
`https://www.gravatar.com/avatar/bb1a9d0a...`
I tried to compute some of the hashes myself in the JavaScript console using [this](https://github.com/xibre/FastMD5/blob/master/build/md5.min.js) md5-function:
```
> md5("M.P.Sijm@...")
< "bb1a9d0a..."
> md5("m.p.sijm@...")
< "bf363487..."
```

**Comment by ticky** [comment]
Ooh! Good catch!

**Comment by toolmantim** [comment]
This should all be fixed now!

Thanks again for reporting this, and sleuthing what was causing it 👏🏼❤️
