### ISSUE TITLE
Feature Request:  Ability to retry step even if it's successful

### ISSUE THREAD

**Issue by thewoolleyman** [buildkite/frontend#328]
Sometimes I want to do this, e.g. for a long-running build with one step I'm trying to debug for flakiness, or to test a step which builds and publishes artifacts, and should be a no-op download if run subsequently for the same SHA.

**Comment by keithpitt** [comment]
This is a thing now!

https://buildkite.com/docs/pipelines/command-step#manual-retry-attributes

There's some new configuration you can pass to `retry.manual` inside a command to control this 🚀
