### ISSUE TITLE
Feature request: authorize via Github

### ISSUE THREAD

**Issue by horpto** [buildkite/frontend#381]
You say that the buildkite supports Github integration. But necessity to create via email and/or other unwanted actions obstructs a bit for a simple testing of buildkite.

Sorry, frontend can be bad place for this issue,

**Comment by toolmantim** [comment]
Thanks for the feedback! We'd definitely love to add something like that. Could you open a ticket here instead: https://github.com/buildkite/feedback/issues That way other people can see it, and we can properly track it etc. Thanks, that'd be much appreciated!

**Comment by toolmantim** [comment]
I'll close this one for now.
