### ISSUE TITLE
Page hangs when you spell your team name wrong

### ISSUE THREAD

**Issue by tigris** [buildkite/frontend#42]
When you're a complete idiot (like myself), you spell things wrong all the time. Of course, there is an invention called _bookmarks_ to solve this problem, but alas, when you head to https://buildkite.com/org?team=non-existent-team you get a page hang.

I guess it would be nicer to get a 404 or some kind of message. RESTful i guess the URL is accurate, so 404 may not be technically correct since it's invalid query params causing the issue. 400 bad request maybe. Or just a screen message. I'll leave that up to your capable hands.

**Comment by keithpitt** [comment]
This is fixed(ish) now :)
