### ISSUE TITLE
Issues deleting team member ...

### ISSUE THREAD

**Issue by justinhennessy** [buildkite/frontend#43]
Going to https://buildkite.com/organizations/<org>/teams/development and clicking on "remove" doesn't do anything.

Also looked at browser debug and there was no call actioned from a click.

**Comment by keithpitt** [comment]
I've just confirmed locally that it doesn't work :(

Will fix today! Sorry about the regression!

**Comment by keithpitt** [comment]
All fixed @justinhennessy! Thanks for reporting :)
