### ISSUE TITLE
GitHub repository line should trim leading/trailing whitespace

### ISSUE THREAD

**Issue by efung** [buildkite/frontend#46]
I accidentally had a leading space in my repository name, which the UI accepted. However, when the agent tried to check out the code, I got the misleading message that:

```
Cloning into '.'...
Permission denied (publickey).
fatal: Could not read from remote repository.
```

The command-line output shows that the repo name is quoted:

```
$ cd "/var/lib/buildkite-agent/builds/ubuntu-1404-10.232.1.48/example/repo"
$ git clone -v -- " git@github.com:example/repo.git" .
```

Screenshot:
<img width="474" alt="screen shot 2016-08-17 at 11 44 51 am" src="https://cloud.githubusercontent.com/assets/301094/17743209/e4bca2cc-6470-11e6-8690-aa95d929a3c3.png">

**Comment by keithpitt** [comment]
Good catch @efung! I've made a fix on our end so if you enter a repository with a space like that again, we'll make sure it's stripped as we save it.

Thanks for letting us know!
