### ISSUE TITLE
Show "Wait" line in lower step list

### ISSUE THREAD

**Issue by underscorebrody** [buildkite/frontend#47]
A "Wait" is represented by the little pointer arrow in the top list of steps, but has no visual representation in the lower list. It would be helpful when scrolling through a long list of steps to see where the "Wait"s occurred. # #

**Comment by keithpitt** [comment]
Ah this is an interesting idea! I think we've toyed with it before, but couldn't get it looking right.

That page is due for a bit of a refresh, so we'll make sure we can somehow incorporate this into a new design. Thanks for the feedback!
