### ISSUE TITLE
Triggered builds with retried steps don't update parent

### ISSUE THREAD

**Issue by underscorebrody** [buildkite/frontend#48]
Scenario:
- Build A triggers build B on another pipeline
- Build B has one failing job, causes build A to have a failing state 
- Failing job is retried and passes, causing build B to now have a passing state
- Build A remains in a failing state

(Note: The reference to build B on the build A page also does not go into the "in progress" state when the job on build B is being retried)

**Comment by keithpitt** [comment]
Ah yes! I've seen this issue before. The `trigger` step hasn't actually been fully shipped yet, and this is one of the last outstanding issues for it. When we announce it properly we'll make sure to have this problem fix.

Thanks for letting us know! I'll close this issue for now :)
