### ISSUE TITLE
Buildkite logo clickable area is smaller vertically than other menu items

### ISSUE THREAD

**Issue by ticky** [buildkite/frontend#51]
<img width="571" alt="screen shot 2016-09-08 at 12 03 25 pm" src="https://cloud.githubusercontent.com/assets/282113/18334649/4c1c9c22-75bc-11e6-8ed3-69ec662b7e72.png">
<img width="720" alt="screen shot 2016-09-08 at 12 03 25 pm-2" src="https://cloud.githubusercontent.com/assets/282113/18334657/57c1c160-75bc-11e6-9b08-ce93d564762a.png">

**Comment by toolmantim** [comment]
Yes! Nice find
