### ISSUE TITLE
Block step modal content gets cut off if there are too many selects/text inputs inside.

### ISSUE THREAD

**Issue by alfredlucero** [buildkite/frontend#535]
I am using a Mac laptop with a Chrome browser and encounter the block step modal sometimes gets cut off at the top to the point I cannot scroll any higher and some inputs, title, and closing X button of the modal get cut off if there are too many selects/text input fields in the block step modal. I can scroll down to click 'Continue' which is good though. I've been experimenting with adding a bunch of fields and ran into this issue in our pipelines.
<img width="621" alt="screen shot 2018-08-07 at 3 10 09 pm" src="https://user-images.githubusercontent.com/11841941/43805304-1cdcaf24-9a54-11e8-99c6-58ec9fcfa9e6.png">

**Comment by keithpitt** [comment]
Hey @alfredlucero - I just pushed out a fix for this. Can you confirm the modal isn't getting cut off anymore?
