### ISSUE TITLE
[Feature request]: Enable ability to generate hyperlink directly to build step

### ISSUE THREAD

**Issue by twilco** [buildkite/frontend#766]
You are obviously able to share a hyperlink to a specific build:

https://buildkite.com/my-org/project/builds/322

But it would be nice to also be able to link directly to a specific build step.  This might look something like:

https://buildkite.com/my-org/project/builds/322#integration-test-temp-deployment

**Comment by ticky** [comment]
Hi @twilco, you can actually link to specific steps already, we just only support the job UUID!

You can copy direct links from the build header, or click to open the job you want, and then copy the URL from your address bar.

**Comment by twilco** [comment]
Wow, not sure how I missed this.  Thanks!
