### ISSUE TITLE
agent token copy shouldn't retain in a clipboard manager

### ISSUE THREAD

**Issue by nhooyr** [buildkite/frontend#788]
When I use the copy for my agent token, it gets put in my clipboard manager's history.

If I copy a password on 1password though, the password is not retained. I'm not sure how `1password` does this but buildkite should do this too. I believe GitHub also handles this correctly when copying an access token

**Comment by ticky** [comment]
Hi @nhooyr, unfortunately whatever your clipboard manager is doing, it’s non-standard. There’s no option in the web clipboard APIs to mark something as “sensitive,” and it’s likely that your clipboard manager is itself identifying clips from 1Password as such. Without knowing what you’re using, or what it’s doing, there’s not really much we can do other than advise you to be careful!

**Comment by nhooyr** [comment]
Just verified GitHub also doesn't handle this correctly, my bad. 1password is a desktop app so there must be something in the macOS clipboard API or as you said my clipboard manager is detecting which app I copied from.
